### ISSUE TITLE
Enable returning `SQL_DOUBLE` type as a JS Number

### ISSUE THREAD

**Issue by abmusse** [IBM/nodejs-idb-connector#104]
**Describe the solution you'd like**
Enable returning `SQL_DOUBLE` type as a `JS Number` instead of a `JS String` if `dbstmt.asNumber(true)` is set.

Contiuation of #64 

Currently only `SQL_INTEGER`, `SQL_SMALLINT`, `SQL_DECIMAL`, and `SQL_NUMERIC` types will be returned as JS Number when `dbstmt.asNumber(true)` is set.

**Additional context**

![image](https://user-images.githubusercontent.com/33973272/72744908-1dc64680-3b74-11ea-9f80-555aaa6f7c1d.png)

[Source](https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_74/db2/rbafzhctabl.htm)

According to the [docs](https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_74/db2/rbafzch2num.htm):
```
Floating-point
A single-precision floating-point number is a 32-bit approximate representation 
of a real number. The range of magnitude is approximately 
1.17549436 × 10-38 to 3.40282356 × 1038.

A double-precision floating-point number is a IEEE 64-bit approximate representation 
of a real number. The range of magnitude is approximately
 2.2250738585072014 × 10^-308 to 1.7976931348623158 × 10^308.

Single-precision floating-point is generally accurate to 7 digits of precision.
Double-precision floating-point is generally accurate to 15 digits of precision.

```

JavaScript Number has the following min and max values:

[Number.MAX_VALUE](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_VALUE) = `1.7976931348623157e+308`

[Number.MIN_VALUE](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MIN_VALUE) = `5e-324`

Seems like the JS Number Class will be able to hold the `SQL_DOUBLE` type.

We can probably just add a case for `SQL_DOUBLE` [here](https://github.com/IBM/nodejs-idb-connector/blob/master/src/db2ia/dbstmt.cc#L2268)

@dmabupt @kadler @markdirish @ThePrez  Do you think this would work?

**Comment by dmabupt** [comment]
resolved with commit 1b4d8d1

**Comment by dmabupt** [comment]
idb-connector v1.2.5 is released to fix this issue.

**Comment by abmusse** [comment]
Nice! 

I think we should also add test cases selecting and fetching Min and Max values for `DOUBLE, FLOAT, REAL` types to confirm the behavior. Similar to how we have done [here](https://github.com/IBM/nodejs-idb-connector/blob/master/test/statementTest.js#L393).

**Comment by kadler** [comment]
Note that precision and scale returned for `REAL` and `DOUBLE` columns is _not_ the same as for `DECIMAL`/`NUMERIC` columns. It does not contain the number of digits, but instead precision will be either 4 (`REAL`) or 8 (`DOUBLE`), which is the size in bytes that it takes up.

Code like this is not correct:
https://github.com/IBM/nodejs-idb-connector/blob/1b4d8d19b0230e553f542c1b2ea74c0ce5e52231/src/db2ia/dbstmt.cc#L2272
https://github.com/IBM/nodejs-idb-connector/blob/1b4d8d19b0230e553f542c1b2ea74c0ce5e52231/src/db2ia/dbstmt.cc#L2102

**Comment by dmabupt** [comment]
Hello,
@kadler commit bcb1962 fixed it.
@abmusse the above commit added the test cases.
