### ISSUE TITLE
feat: Add bindParameters() that accepts an array of values

### ISSUE THREAD

**Issue by abmusse** [IBM/nodejs-idb-connector#111]
**Is your feature request related to a problem? Please describe.**

Currently whenever we want to bind a parameter we need to pass a 2D array to [dbstmt.bindParam](https://github.com/IBM/nodejs-idb-connector/tree/master/docs#dbstmtbindparamparams-callback)

```js
statement.bindParam([
    [9997, IN, NUMERIC],
    ['Johnson', IN, CHAR],
    ['A J', IN, CHAR],
    ['453 Example', IN, CHAR],
    ['Fort', IN, CHAR],
  ]);
```
This works ok but i think we can simplify things a bit.

**Describe the solution you'd like**

I purpose we add another method `dbstmt.bindParameters()` to accept an array of values instead of array of arrays.

```js
dbstmt.bindParameters([9997, 'Johnson', 'A J', 453 Example','Fort'])
```
We can use [SQLDescribeParam](https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_73/cli/rzadpfndescprm.htm) to get back the type of the parameter.

In fact we already make the call [here](https://github.com/IBM/nodejs-idb-connector/blob/master/src/db2ia/dbstmt.cc#L2368)

I think we can set the inout to IN unless we are binding a parameter to a procedure.

In that case we can use [SQLProcedureColumns](https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_73/cli/rzadpfnprcco.htm) to get a list of input and output parameters associated with a procedure.

Or maybe we could always set the inout type to `SQL_PARAM_INPUT_OUTPUT`.

That way the user does not have to specify the inout type or data type when using `dbstmt.bindParameters`.

**Comment by dmabupt** [comment]
This would be great but I still have some concerns according to the CLI doc -- 

- [SQLDescribeParam()](https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_72/cli/rzadpfndescprm.htm) 
`SQLDescribeParam() does not return the type (input, output, or both input and output) of a parameter in an SQL statement. Except in calls to procedures, all parameters in SQL statements are input parameters. To determine the type of each parameter in a call to a procedure, an application calls SQLProcedureColumns().`
- [SQLProcedureColumns()](https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_72/cli/rzadpfnprcco.htm)
`Because calls to SQLProcedureColumns() in many cases map to a complex and thus expensive query against the system catalog, they should be used sparingly, and the results saved rather than repeating calls.`

**Comment by kadler** [comment]
@abmusse please fix your example to use `bindParameters` instead of `bindParameter`.

**Comment by kadler** [comment]
@dmabupt There should be no harm in always binding `SQL_PARAM_INPUT_OUTPUT`. Anything that's input only will just leave the buffer unmodified.

**Comment by kadler** [comment]
I think we could get by without making a new API. Instead, for each parameter passed, check whether an array or a value was passed in and act appropriately.

While I think we _can_ get by without making a new API, I'd recommend we still do and just make `bindParam` a deprecated alias of it.

**Comment by dmabupt** [comment]
> I think we could get by without making a new API. Instead, for each parameter passed, check whether an array or a value was passed in and act appropriately.
> 
> While I think we _can_ get by without making a new API, I'd recommend we still do and just make `bindParam` a deprecated alias of it.

PR #112 is ready for your review.

BTW, the behavior has changed in the new API. 

Previously we only get the `out` & `in_out` parameters output.
But now the new API can not distinguish them, so all the parameters will be in the output.

For example, the most famous procedure -- `call QXMLSERV.iPLUG512K(?,?,?,?)`
Its parameter list is --
```
[ipc, IN, CHAR],
[ctl, IN, CHAR],
[xmlIn, IN, CLOB],
[xmlOut, OUT, CLOB],
```
When we run `execute()` against it. 

Previously the output array has 1 element - the last output parameter `xmlOut`.
Now all the 4 parameters will be in the output array!

**Comment by dmabupt** [comment]
> I think we could get by without making a new API. Instead, for each parameter passed, check whether an array or a value was passed in and act appropriately.
> 
> While I think we _can_ get by without making a new API, I'd recommend we still do and just make `bindParam` a deprecated alias of it.

Hello @kadler , Seems the code of [DbStmt::bindParams](https://github.com/IBM/nodejs-idb-connector/pull/112/files#diff-b307b5c576890c839b53066078db965cR2477-R2751) is too much now. 

So I think maybe we should keep the old `DbStmt::bindParams()` untouched for best back-ward compatibility. And add a brand new C function `DbStmt::bindParameters()` only for the new JS API `bindParameters()`. 

| JS API | C API | Parameters | Output |
|  ----  | ----  | ----  | ----  |
| bindParams() | DbStmt::bindParams() | 2-D array | ONLY output params |
| bindParameters() | DbStmt::bindParameters() | 1-D array  | ALL params |

**Comment by dmabupt** [comment]
PR https://github.com/IBM/nodejs-idb-connector/pull/112 has been merged. Close this.
