### ISSUE TITLE
Get Enumeration to FieldTypes

### ISSUE THREAD

**Issue by joaojmendes** [IBM/nodejs-idb-connector#115]
Please add enum to FieldTypes.

When we get fieldTypes(i) we get number id not the description of fieldtype. 

thank you.

**Comment by kadler** [comment]
While I agree it would be better to return a more useful type string, these types can be compared to those exported here: https://github.com/IBM/nodejs-idb-connector/blob/master/lib/db2a.js#L337-L377

**Comment by joaojmendes** [comment]
Thank tou! Is that I use now. 😊

**Comment by dmabupt** [comment]
Actually we have this internal used function [getSQLType](https://github.com/IBM/nodejs-idb-connector/blob/master/src/db2ia/dberror.h#L103). But it is only used for debug currently.

**Comment by dmabupt** [comment]
I would like to add a new function (maybe called **fieldInfo**) to provide all the information of the column, including type, width, nullable, etc.

**Comment by dmabupt** [comment]
Hello @joaojmendes ,
The PR is drafted at #118 . If no problem, I will merge it later.

**Comment by joaojmendes** [comment]
Hello, @Xu Meng<mailto:notifications@github.com>

Thank you for the answer.

Yes seem a good solution to have one object with all information about column.


Thank you !
João

**Comment by dmabupt** [comment]
Close this issue since idb-connector v1.2.9 is released now. This new version contains the new API to resolve the issue.
