### ISSUE TITLE
Statement with bindParam equal does not work correctly

### ISSUE THREAD

**Issue by jhonnattan123** [IBM/nodejs-idb-connector#127]
- Node.js version: **14.6.0**
- idb-connector version: **idb-connector@1.2.9**
- idb-pconnector version: **idb-pconnector@1.0.8**
- IBM i version: **3 7**

**Describe the bug**
the equal operator is supposed to work the same with both a direct query and a prepared query, however they are working differently

**To Reproduce**
```
const { Connection, Statement, IN, CHAR } = require('idb-pconnector');

const sql = 'SELECT * FROM QIWS.QCUSTCDT WHERE CITY = ?';
let bindParams = [ [ 'Dallas2', IN, CHAR  ] ]

let connection = new Connection({ url: '*LOCAL' });
let statement = new Statement(connection);

await statement.bindParam(bindParams);
await statement.execute(sql);
let resultSet = await statement.fetchAll();

```

**Expected behavior**
It is assumed that no record in the test table matches the city Dallas2, since Dallas is actually written without the number 2. but the system still finds Dallas being Dallas ! = Dallas2

**Screenshots**
with bindParam statement
![image](https://user-images.githubusercontent.com/31730855/95367646-5f865100-08ab-11eb-9a8a-365bc1a845d7.png)

normal query
![image](https://user-images.githubusercontent.com/31730855/95369427-cc9ae600-08ad-11eb-83d3-260eee74c87b.png)

**Additional context**
It can be solved by modifying the sentence but it is a waste of resources. ej 
`SELECT * FROM QIWS.QCUSTCDT WHERE CITY = %?%`

**Comment by abmusse** [comment]
CC @dmabupt

**Comment by ThePrez** [comment]
Since the `CITY` column is only 6 characters long, the parameterized condition is presumably getting truncated from "Dallas2" to "Dallas".

**Comment by ThePrez** [comment]
CC @forstie, any insight/thoughts on what the proper behavior is here? Should we instead be throwing truncation warnings/errors?

**Comment by abmusse** [comment]
That makes sense. Looking at the [SQLBindCol](https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_73/cli/rzadpfnbindc.htm#rzadpfnbindc) I see

```
The application must ensure enough storage is allocated for the data
to be retrieved.If the buffer is to contain variable length data, the 
application must allocate as much storage
as the maximum length of the bound column requires; 
otherwise, the data might be truncated.
```

**Comment by jhonnattan123** [comment]
makes sense but the truth is unexpected.
In my opinion, they should behave in the same way as the simple query, as it can lead to unexpected or unwanted results when looking for precision and validation. I think in this case I should not return anything or issue a warning.

**Comment by ThePrez** [comment]
> makes sense but the truth is unexpected.
> In my opinion, they should behave in the same way as the simple query, as it can lead to unexpected or unwanted results when looking for precision and validation. I think in this case I should not return anything or issue a warning.
> 

I agree

**Comment by forstie** [comment]
This looks to be working as expected, although I do have to question only having 6 characters for a city name.

Retrieval assignment:
The length of a string assigned to a variable (but not a parameter or transition
variable) can be greater than the length attribute of the variable. When a string is
assigned to a variable and the string is longer than the length attribute of the
variable, the string is truncated on the right by the necessary number of characters.
When this occurs, an SQLSTATE of '01004' is assigned to the
RETURNED_SQLSTATE condition area item in the SQL Diagnostics Area (or the
value 'W' is assigned to the SQLWARN1 field of the SQLCA).

SQLBindParam has the concept of SQL_SUCCESS_WITH_INFO.
I'm not sure if that or the aforementioned warning would be surfacable here.

**Comment by jhonnattan123** [comment]
> This looks to be working as expected, although I do have to question only having 6 characters for a city name.
> 
> Retrieval assignment:
> The length of a string assigned to a variable (but not a parameter or transition
> variable) can be greater than the length attribute of the variable. When a string is
> assigned to a variable and the string is longer than the length attribute of the
> variable, the string is truncated on the right by the necessary number of characters.
> When this occurs, an SQLSTATE of '01004' is assigned to the
> RETURNED_SQLSTATE condition area item in the SQL Diagnostics Area (or the
> value 'W' is assigned to the SQLWARN1 field of the SQLCA).
> 
> SQLBindParam has the concept of SQL_SUCCESS_WITH_INFO.
> I'm not sure if that or the aforementioned warning would be surfacable here.

> This looks to be working as expected, although I do have to question only having 6 characters for a city name.
> 
> Retrieval assignment:
> The length of a string assigned to a variable (but not a parameter or transition
> variable) can be greater than the length attribute of the variable. When a string is
> assigned to a variable and the string is longer than the length attribute of the
> variable, the string is truncated on the right by the necessary number of characters.
> When this occurs, an SQLSTATE of '01004' is assigned to the
> RETURNED_SQLSTATE condition area item in the SQL Diagnostics Area (or the
> value 'W' is assigned to the SQLWARN1 field of the SQLCA).
> 
> SQLBindParam has the concept of SQL_SUCCESS_WITH_INFO.
> I'm not sure if that or the aforementioned warning would be surfacable here.

in a few hours I will have access to an iseries, I will confirm if the response to SQL_SUCCESS_WITH_INFO arrives. in case it reaches SQL_SUCCESS_WITH_INFO:
What do you think of creating a function or setting in the library that allows you to ignore that response and return as if nothing has been found? (although results were actually found) would be a waste of memory and perhaps a vulnerability. Is there a possibility to modify this behavior from the query?

**Comment by dmabupt** [comment]
I found some code that have potential problems related to this issue.
https://github.com/IBM/nodejs-idb-connector/blob/master/src/db2ia/dbstmt.cc#L2593

The code assumes that the input parameter is always shorter than the column defined length. But in this case, it is not true.

The idb-connector level code does not truncate the input parameter data in the bindParam() function. It may be related to the different behavior. 

Maybe I should truncate the too long input parameters in idb-connector.

**Comment by dmabupt** [comment]
> I found some code that have potential problems related to this issue.
> https://github.com/IBM/nodejs-idb-connector/blob/master/src/db2ia/dbstmt.cc#L2593
> 
> The code assumes that the input parameter is always shorter than the column defined length. But in this case, it is not true.
> 
> The idb-connector level code does not truncate the input parameter data in the bindParam() function. It may be related to the different behavior.
> 
> Maybe I should truncate the too long input parameters in idb-connector.

Ah... The problem is that the bindParam truncates the string while exec not. So it is not the root cause.
And I also can not catch any SQL_SUCCESS_WITH_INFO

**Comment by jhonnattan123** [comment]
> > > This looks to be working as expected, although I do have to question only having 6 characters for a city name.
> > > Retrieval assignment:
> > > The length of a string assigned to a variable (but not a parameter or transition
> > > variable) can be greater than the length attribute of the variable. When a string is
> > > assigned to a variable and the string is longer than the length attribute of the
> > > variable, the string is truncated on the right by the necessary number of characters.
> > > When this occurs, an SQLSTATE of '01004' is assigned to the
> > > RETURNED_SQLSTATE condition area item in the SQL Diagnostics Area (or the
> > > value 'W' is assigned to the SQLWARN1 field of the SQLCA).
> > > SQLBindParam has the concept of SQL_SUCCESS_WITH_INFO.
> > > I'm not sure if that or the aforementioned warning would be surfacable here.
> > 
> > 
> > in a few hours I will have access to an iseries, I will confirm if the response to SQL_SUCCESS_WITH_INFO arrives. in case it reaches SQL_SUCCESS_WITH_INFO:
> > What do you think of creating a function or setting in the library that allows you to ignore that response and return as if nothing has been found? (although results were actually found) would be a waste of memory and perhaps a vulnerability. Is there a possibility to modify this behavior from the query?
> 
> Hello @jhonnattan123, have you got the SQL_SUCCESS_WITH_INFO returned code? I can not get that when debugging the code.
> 
> If this is not an idb-connector issue. I will assume that it is working as expected and add corresponding test cases.


Does that mean that with the last commit now if they should work like the normal query?._

**Comment by dmabupt** [comment]
> Does that mean that with the last commit now if they should work like the normal query?._
> I had problems that day, to put the console log, and I was waiting this week (by issues of work permits) to put the console.log

No, the latest version does not change current behavior. As far as I can see, the truncation does not happen in the idb-connector level.
