### ISSUE TITLE
Running drop schema statement hangs

### ISSUE THREAD

**Issue by abmusse** [IBM/nodejs-idb-connector#128]
* **Node.js version**: v12.18.4
* **idb-connector version**: 1.2.10
* **IBM i version:**: 7.2

**Describe the bug**
When trying to drop a schema the program hangs. Looks like the schema get held by a lock.

**To Reproduce**

I first created a schema via Run Sql Scripts:

![image](https://user-images.githubusercontent.com/33973272/98325122-adc66700-1fb3-11eb-9a93-a965bc1f441d.png)

Then using idb-connector attempted attempted to drop the schema

```js
const { dbconn, dbstmt, SQL_TXN_NO_COMMIT, SQL_TXN_ISOLATION,
 } = require('idb-connector');

  const schema = 'IDBTEST';
  const dropSchema = `DROP SCHEMA ${schema}`;
  const findSchema = `SELECT SCHEMA_NAME FROM QSYS2.sysschemas WHERE SCHEMA_NAME = '${schema}'`

  const connection = new dbconn();
  connection.debug(true);
  let isolationLevel = connection.getConnAttr(SQL_TXN_ISOLATION);
  console.log('BEFORE: Isolation level is: ', isolationLevel);
  connection.setConnAttr(SQL_TXN_ISOLATION, SQL_TXN_NO_COMMIT);
  isolationLevel = connection.getConnAttr(SQL_TXN_ISOLATION);
  console.log('AFTER: Isolation level is: ', isolationLevel);

  connection.conn('*LOCAL');
  const statement = new dbstmt(connection);

  console.log('finding schema...');
  statement.exec(findSchema, (r, e) => {
    if (e) { throw e; }
    console.log('find schema result: ', r);
    statement.closeCursor();
    console.log('dropping schema...');
    statement.exec(dropSchema, (r2, e2) => {
      if (e2) { throw e2; }
      statement.close();
      connection.disconn();
      connection.close();
    });
  });
```

## Output:
![image](https://user-images.githubusercontent.com/33973272/98327035-43fc8c00-1fb8-11eb-8e9c-9d8310a7c074.png)

![image](https://user-images.githubusercontent.com/33973272/98325532-a5226080-1fb4-11eb-9480-03c9608b1f1e.png)

Trying to drop the schema from Run Sql Scripts:

![image](https://user-images.githubusercontent.com/33973272/98326242-67263c00-1fb6-11eb-8e5c-eadcd4db1377.png)

FYI I needed to set the isolation level to no commit to avoid this error:

![image](https://user-images.githubusercontent.com/33973272/98326723-7e195e00-1fb7-11eb-9b04-642c0524239a.png)

@dmabupt  Have you run into this before?

**Expected behavior**
Should be able to drop the schema successfully without hanging

**Comment by kadler** [comment]
When dropping a schema, if there are unsaved journal receivers the job will go in to message wait indefinitely. I suspect that's what's going on here.

You can double check in WRKACTJOB if the status says "MSGW". If so, you can use option 7 on the job to answer the messages. You can also work around this with reply list entries, but they are system-wide and require special authority to set.

**Comment by abmusse** [comment]
Spot on there was a QSQSRVR job in MSGW Status. I Hit option 7 and replied with `I` to continue operation then my code terminated successfully. 

![image](https://user-images.githubusercontent.com/33973272/100643551-d36b3580-32ff-11eb-963f-63a241f5dcaf.png)
