### ISSUE TITLE
Connection Pool

### ISSUE THREAD

**Issue by tonkolviktor** [IBM/nodejs-idb-connector#158]
**Is your feature request related to a problem? Please describe.**
I'd like to use a connection pool in a rest api scenario to avoid creating connections for each request. 

**Describe the solution you'd like**
Something like: https://www.npmjs.com/package/odbc#Pool

**Describe alternatives you've considered**
I could not find anything in the readme, but I may have missed it.
I'm afraid I have to implement something myself!?

**Comment by abmusse** [comment]
There a connection pool available in [idb-pconnector](https://github.com/IBM/nodejs-idb-pconnector#dbpool).

**Comment by tonkolviktor** [comment]
yes, thanks tested and works perfect! (maybe you could mention on the main page that there is an other lib ;) )
