### ISSUE TITLE
the sql state error seems to be fixed, but we have a different issue

### ISSUE THREAD

**Issue by kadler** [IBM/nodejs-idb-connector#165]
> the sql state error seems to be fixed, but we have a different issue
> any numeric values being returned from a stored procedure are not formatted as they were before.
> numbers come back in the result set looking like this:  36367754\u0000

_Originally posted by @mikebohlen in https://github.com/IBM/nodejs-idb-connector/issues/147#issuecomment-1318731491_

Looks like we're including the trailing null terminator when we convert back in to a Javascript string. Likely CLI is including this in the length, even though it shouldn't so we might have to adjust it.

**Comment by mikebohlen** [comment]
Ok, thanks let me know..

**Comment by mikebohlen** [comment]
if you need anything

**Comment by abmusse** [comment]
This looks like a duplicate of https://github.com/IBM/nodejs-idb-connector/issues/169
