### ISSUE TITLE
Case-insensitive searching

### ISSUE THREAD

**Issue by abmusse** [IBM/nodejs-idb-connector#33]
**[Original report](https://bitbucket.org/litmis/nodejs-idb-connector/issue/32) by Kristopher Baehr (Bitbucket: [krisbaehr](https://bitbucket.org/krisbaehr), GitHub: [krisbaehr](https://github.com/krisbaehr)).**

----------------------------------------

Is there an equivalent to "exec sql SET OPTION SRTSEQ=*LANGIDSHR" as in an RPGLE program? This tells the program to perform case-insensitive searches when executing SQL. Could we run this before running a statement, or by setting a statement option? If this was a setting on a statement, not a connection that would be great. We can always use the upper() and lower() sql functions if necessary. Any help is appreciated.

**Comment by dmabupt** [comment]
Consulted some Db2 experts. This feature is not supported. 

It depends on the user to handle the case-insensitive searching like `where A=‘a' or A=upper('a')`
