### ISSUE TITLE
Connection pooling

### ISSUE THREAD

**Issue by abmusse** [IBM/nodejs-idb-connector#5]
**[Original report](https://bitbucket.org/litmis/nodejs-idb-connector/issue/4) by Aaron Bartell (Bitbucket: [aaronbartell](https://bitbucket.org/aaronbartell), GitHub: [aaronbartell](https://github.com/aaronbartell)).**

----------------------------------------

You can learn more of the need for connection pools by looking at [this thread](https://bitbucket.org/litmis/nodejs-itoolkit/issues/8/hapijs-and-itoolkit-async-issue#comment-37436818) which includes the eventual [solution](https://bitbucket.org/litmis/nodejs-itoolkit/issues/8/hapijs-and-itoolkit-async-issue#comment-37444151).  I also wrote an article about the topic in [MCPressOnline](http://krengel.tech/mcpress-node-db-pool).

**This Issue is to discuss:**

- Whether there is agreement to add connection pool capabilities to this repo (I believe it should be included).
- What features should be in a connection pool.
- Whether the code in [this article](http://krengel.tech/mcpress-node-db-pool) is "good enough" for an initial implementation.
- Implications for the [Node.js iToolkit](https://bitbucket.org/litmis/nodejs-itoolkit) if any.

*UPDATE 2017-08-30**
There are discussions in [this issue](https://bitbucket.org/litmis/nodejs-idb-connector/issues/5/db2sock-and-node-db2-impacts) that will effect this issue.

**Comment by dmabupt** [comment]
Since the idb-pconnector implementation is already available. Close this for now.
