### ISSUE TITLE
Skip Build Unless Installing on IBM i

### ISSUE THREAD

**Issue by abmusse** [IBM/nodejs-idb-connector#54]
**[Original report](https://bitbucket.org/litmis/nodejs-idb-connector/issue/53) by David Russo (Bitbucket: [DavidRusso](https://bitbucket.org/DavidRusso), GitHub: [DavidRusso](https://github.com/DavidRusso)).**

----------------------------------------

I work on a package that installs on multiple platforms, including IBM i. I've put idb-connector under optionalDependencies in my package.json -- this allows NPM to proceed with installing my package on non-IBM i platforms, where idb-connector obviously does not work. Programming logic in my package then selects the appropriate database connector for the appropriate platform.

This allows me to install on any platform, but I get a lot of unnecessary output and error messages when installing on non-IBM i platforms because NPM goes through the motions of trying to build idb-connector.  To see what I mean, try 'npm install profoundjs' on a Windows PC. 

I'm wondering if it's possible to set up so that NPM does not try to build/install idb-connector unless installing on IBM i.

Maybe it's just a matter of setting the 'os' key in idb-connector's package.json?

https://docs.npmjs.com/files/package.json#os

**Comment by dmabupt** [comment]
Hello @DavidRusso , I have upgraded idb-connector to 1.1.8 which contains the changes. You may verify it now.

**Comment by ThePrez** [comment]
This change does not work for  AIX. Can you make it for AIX too?

**Comment by kadler** [comment]
I'm not sure how it could *not* work on AIX, since it only references "aix" for which builds to skip. Or do AIX builds put the version in the OS string?

**Comment by ThePrez** [comment]
The build is not skipped on AIX as it should be, and proceeds to fail.

**Comment by abmusse** [comment]
In our package.json we specify `"os": "aix"`

![image](https://user-images.githubusercontent.com/33973272/52432726-d5cc2200-2ad0-11e9-903d-53cbbaef4ecc.png)



![image](https://user-images.githubusercontent.com/33973272/52432956-73275600-2ad1-11e9-83d0-383c21566329.png)



For us process.platform returns "aix" so insall script continues searches for prebuilt binaries and cannot find any matching  ` "package_name": "{module_name}-v{version}-{node_abi}-ibmi-{arch}.tar.gz"`

Then falls back to build from source and fails.

![image](https://user-images.githubusercontent.com/33973272/52433525-e41b3d80-2ad2-11e9-87d6-7ccb305d74fc.png)

For it to skip on AIX we would need to dig into how process.platform is determined or find another work around.

`os.type()` returns `OS400` appropriately.

Maybe we can override npm install to run our own install script. An example of doing this woul be [Appmetrics](https://github.com/abmusse/appmetrics/blob/master/package.json#L33) overides install script to run `node extract_all_binaries.js || node-gyp rebuild`

**Comment by kadler** [comment]
Why does it need to work on AIX in the first place? This requires libdb400, which isn't available on AIX anyway.

**Comment by abmusse** [comment]
Right it cannot work on AIX. The failure is expected

Our package.json whitelists AIX as our only supported platform

On every other platform it will show something like

```
Unsupported platform for idb-connector
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for idb-connector@1.1.8: wanted {"os":"aix","arch":"any"} 
```

but on AIX it will actually try to build the project and fail.

I guess we should just clearly Iterate in our readme this package is only for IBM i

**Comment by dmabupt** [comment]
PR #57 is created.

**Comment by ThePrez** [comment]
This is holding up React.js support on IBM i, so I consider this a high-priority item (or working to find alternative implementation for default-gateway)

**Comment by kadler** [comment]
@ThePrez I'm trying to figure how that could be. Can you link to that issue?

**Comment by abmusse** [comment]
@kadler 
https://github.com/silverwind/default-gateway/issues/5
https://github.com/silverwind/default-gateway/issues/10

**Comment by ThePrez** [comment]
We could skip the native parts in the .gyp file based on an "os400" condition. That would be pretty clean

**Comment by silverwind** [comment]
`npm` has, as discovered issues with honoring the `os` property in some cases, so it it is not enough to prevent a build on non-AIX. Anyways, I have now decided to only accept AIX support in my module if it is a pure-JS implementation. Native modules are just not the headaches they bring in a cross-platform module.

**Comment by dmabupt** [comment]
idb-connector [v1.1.9](https://www.npmjs.com/package/idb-connector) is released now. It takes the code from PR #58
