### ISSUE TITLE
Adopt airbnb style guide for tests and examples

### ISSUE THREAD

**Issue by abmusse** [IBM/nodejs-idb-connector#60]
We should lint and cleanup the following:

- tests
-  examples in main README and docs/README.md

To use [airbnb style guide](https://github.com/airbnb/javascript) used across our other open source JavaScript projects.

To setup eslint and airbnb eslint config with vscode reference this [article](https://travishorn.com/setting-up-eslint-on-vs-code-with-airbnb-javascript-style-guide-6eb78a535ba6)

**Comment by dmabupt** [comment]
@abmusse Since the airbnb eslint module only uses .eslintrc.js, could we remove the .eslintrc file?

**Comment by dmabupt** [comment]
commit c2a78fe made the eslint and mkdownlint changes.
