### ISSUE TITLE
AS400 - RPG Programs debug when triggered from node.

### ISSUE THREAD

**Issue by sridhar7290** [IBM/nodejs-idb-connector#61]
Hi All

I would like to know if there is anyway to debug AS400 programs when called from Node.Js applications.
As it is a stateless im unable to capture the Job Details to do a service job and debug.

Thanks in advance
Sri

**Comment by abmusse** [comment]
@sridhar7290 
Looks like this issue may be a duplicate of https://github.com/IBM/nodejs-itoolkit/issues/39

Was resolved by: https://github.com/IBM/nodejs-itoolkit/issues/39#issuecomment-468461014
