### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by giammalab** [IBM/nodejs-idb-connector#89]
Hi everybody, i'am trying to install idb-connector on an IBM i V7r2 partition.
Attached is the log of my last try to install.
Additional info from my QSH 
> node -v                                         
  v10.16.3                                        
  $                                               
> npm -v                                          
  6.9.0                                           
  $                                               
> echo $PATH                                      
  /QOpenSys/pkgs/bin:/usr/bin:.:/QOpenSys/usr/bin 
  $                                               

[2019-09-02T14_48_41_402Z-debug.log](https://github.com/IBM/nodejs-idb-connector/files/3566546/2019-09-02T14_48_41_402Z-debug.log)

**Comment by kadler** [comment]
Relevant line is

```
1205 warn lifecycle npm is using /QOpenSys/pkgs/lib/nodejs10/bin/node but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
```

You need to add `/QOpenSys/pkgs/lib/nodejs10/bin` to the `PATH` environment variable or pass `--scripts-prepend-node-path` to `npm`.

**Comment by kadler** [comment]
It seems you can also set this flag to always be enabled with `npm config`, eg. `npm config set scripts-prepend-node-path auto`

**Comment by dmabupt** [comment]
Hello @kadler 
Did you recreate the issue on your system? I may need a recreation to verify the code change. (The installation works fine on my system)

**Comment by dmabupt** [comment]
Hello @giammalab , Do you accept the solutions provided by @kadler ? I will close this issue if no further question.
> 
> You need to add `/QOpenSys/pkgs/lib/nodejs10/bin` to the `PATH` environment variable or pass `--scripts-prepend-node-path` to `npm`.

**Comment by dmabupt** [comment]
Close this since we have a workaround for the issue.
