### ISSUE TITLE
dbconn.conn authentication

### ISSUE THREAD

**Issue by krisbaehr** [IBM/nodejs-idb-connector#93]
I've observed that specifying a bogus password to conn() actually works most of the time. Let's assume I normally connect like this: connection.conn('PROD', 'user', 'password'). The following are also valid: 
 - connection.conn('PROD', 'user', 'password5')
 - connection.conn('PROD', 'user', '1')
 - connection.conn('PROD', 'user', 'this-is-bogus')

The following throw authentication errors (SQLSTATE=08001 SQLCODE=-30082):
 - connection.conn('PROD', 'user', '')
 - connection.conn('PROD', 'user', ' ')
 - connection.conn('PROD', 'user5', 'password')
 - connection.conn('PROD', 'u', 'password')

I understand that it's probably using my job's user to establish the connection but it's misleading if that is what's happening. Are the optionally provided username a password only used when connecting to *LOCAL? Some clarification would be good. Maybe conn() could throw an error if providing user id and password in cases where it would be ignored?

I also noticed that an invalid user always produces the error. If the user is being ignored, why would this even matter? And if the user matters, wouldn't the password as well?

Just a few questions. Thanks, guys!

**Comment by abmusse** [comment]
Interesting, when I tried specifying a bogus password and specified the user with an empty password `.conn` returned an error

### Using this script:

```js
    // Usage: `DBUSER=USER DBPASS=PASS node test.js

    const { dbconn } = require('idb-connector');

    // Allows empty string DBUSER or DBPASS
    if (process.env.DBUSER == undefined || process.env.DBPASS == undefined) {
       console.error('\n\nDBUSER & DBPASS ENV VARS MUST BE SPECIFIED\n\n');
       process.exit();   
    }

    new dbconn().conn('*LOCAL', process.env.DBUSER, process.env.DBPASS);

    console.log('Done!');

```

```
$  DBUSER=MYUSER DBPASS=bogus node test.js 
USER: MYUSER
PASS: bogus
/home/issues/idb-issue-93/test.js:11
    new dbconn().conn('*LOCAL', process.env.DBUSER, process.env.DBPASS);
                 ^

Error: SQLSTATE=08001 SQLCODE=-30082 Authorization failure on distributed database connection attempt.
```

```
$   DBUSER=MYUSER DBPASS="" node test.js
USER: MYUSER
PASS: 
/home/issues/idb-issue-93/test.js:11
    new dbconn().conn('*LOCAL', process.env.DBUSER, process.env.DBPASS);
                 ^

Error: SQLSTATE=08001 SQLCODE=-30082 Authorization failure on distributed database connection attempt.
```

The above is what I would expect to happen.

`*LOCAL` Is a special case where the current user profile is used therefore no need to specify the username and password.

**Comment by ThePrez** [comment]
> `*LOCAL` Is a special case where the current user profile is used therefore no need to specify the username and password.

@abmusse , I think you are confusing `*LOCAL` (database) with `*CURRENT` (username). Even connecting to `*LOCAL`, a bogus password should fail. 

We should do some isolation to verify whether or not the proper (incorrect) values are indeed being passed to `SQLConnect()`.

**Comment by ThePrez** [comment]
I think this may be related. The username and password are not revalidated if the connection object is already connected. @krisbaehr, are you using the same connection object and invoking `conn()` multiple times? Or fresh connection objects? 

https://github.com/IBM/nodejs-idb-connector/blob/5e753bb69c9fbbd192b5f248def9e498bdb5a2d4/src/db2ia/dbconn.cc#L192

**Comment by kadler** [comment]
FYI, non-server mode connections *always* connect as the current user and need no password. Previously this was silently ignored, but I thought there was PTFs to change this behavior so at least you must pass an empty string or NULL, but I would have to do more investigation to be sure - John Eberhard would know more.
