### ISSUE TITLE
Character not display correctly  when using CCSID 836 for specified field

### ISSUE THREAD

**Issue by zhangwenzhuo** [IBM/nodejs-idb-connector#96]
Hi , I am reading the AS400 from old existing file , some field display correctly when using CCSID 935,
However in the same file , there are other fileds using difference CCSID ,which it is 836 and fail to display correct symbol.

**Comment by dmabupt** [comment]
Hello @zhangwenzhuo , 
Are these fileds with CCSID 836 displayed correctly with other tools? Or it only fails with idb-connector?

**Comment by dmabupt** [comment]
CCSID 836 is a single byte charset. It can only represent these characters -- ftp://ftp.software.ibm.com/software/globalization/gcoc/attachments/CP00836.pdf

CCSID 935 is a double bytes charset. It can represent all 835 charset + many Chinese characters.

Acturally, 935=836+837

So if you encode any Chinese characters in CCSID 836, they can not be displayed correctly.

**Comment by zhangwenzhuo** [comment]
@dmabupt  the file level ccsid is 935, and the field level ccsid is 836, i resolve the display issue workaround solution is using SQL convert  ,such as " select cast( field as varchar(20) CCSID 935) as newfield"
